version: "3.9"
services:
  # SOURCE : https://hub.docker.com/r/prestashop/prestashop/
  prestashop:
    image: prestashop/prestashop:1.7-7.3-apache
    restart: always
    networks:
      - prestashop
    ports:
      - 8080:80
    links:
      - mariadb:mariadb
    depends_on:
      - mariadb
    volumes:
      - ./:/var/www/html
      - ./modules:/var/www/html/modules
      - ./themes:/var/www/html/themes
      - ./override:/var/www/html/override
    environment:
      - PS_DEV_MODE=1
      - PS_INSTALL_AUTO=0
      - DB_NAME=prestashop
      - DB_SERVER=mariadb
      - DB_USER=root
      - DB_PASSWD=mycustompassword

  # SOURCE : https://hub.docker.com/_/mariadb
  mariadb:
    image: mariadb
    restart: always
    networks:
      - prestashop
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=prestashop
      - MYSQL_ROOT_PASSWORD=mycustompassword

  # SOURCE : https://hub.docker.com/_/phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    networks:
      - prestashop
    links:
      - mariadb:mariadb
    ports:
      - 8081:80
    depends_on:
      - mariadb
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=mycustompassword

networks:
  prestashop:

volumes:
  db_data:
